[package]
name = "v_archive_rs"
version = "0.1.0"
edition = "2021"
description = "A Rust library for V-Archive"
license = "MIT"

[dependencies]
ureq = "2.12.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde-this-or-that = "0.4.2"
